---
efiBootLoader: "grub"
grubInstall:   "grub-install"
grubMkconfig:  "grub-mkconfig"
grubCfg:       "/boot/grub/grub.cfg"
grubProbe:     "grub-probe"
efiInstallerFlags: [ "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=slyme-os" ]
installEFIFallback: true
