---
backend: pacman

operations:
  - install:
      - base
      - base-devel
      - linux-zen
      - linux-zen-headers
      - linux-firmware
      - grub
      - efibootmgr
      - networkmanager
      - zsh
      - neovim
      - git
      - python
      - python-pip
      - kitty
      - xorg-server
      - xorg-xinit
      - ttf-jetbrains-mono
      - noto-fonts
      - pipewire
      - pipewire-pulse
      - wireplumber
      - sudo
