---
efi:
  mountPoint:      "/boot/efi"
  recommendedSize: "300MiB"
  minimumSize:     "100MiB"

userSwapChoices:
  - none
  - small
  - suspend
  - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true
defaultFsType: "ext4"
availableFsTypes:
  - ext4
  - btrfs
  - xfs
