---
showSupportUrl:        true
showKnownIssuesUrl:    true
showReleaseNotesUrl:   false

requirements:
  requiredStorage:    10
  requiredRam:        2.0
  internetCheckUrl:   "https://google.com"
  check:
    - storage
    - ram
    - power
  required:
    - storage
    - ram
